### ISSUE TITLE
Incluir field Gols no Model Player?

### ISSUE THREAD

**Issue by raphael-foliveira** [nicklima-amigos/football-mm#62]
Parando pra pensar aqui, pensei que talvez seja interessante que os gols feitos nas partidas estejam vinculados a um autor (Player).

Nesse caso, me parece necessário a criação de uma nova entidade "Goal", que teria referências tanto para um jogador (Player) quanto para uma partida ou jogo (Match / Game), o que por sua vez talvez criasse a necessidade de criar um ancestral comum para que Match e Game possam herdar dele, facilitando as relações do Goal com essas entidades.
A criação da entidade "Goal" também vai permitir que possamos mapear com facilidade a quantidade de gols marcados por cada jogador, facilitando o acesso a um dos dados que podem ser importantes para exibir numa eventual tela de estatísticas individuais de cada jogador.

O que os senhores acham da idéia? Caso achem interessante, tem sugestões para que isso seja implementado de uma melhor maneira?

**Comment by nicolas-limadev** [comment]
Rapha, analisando isso, temos que pensar também que não existe só gols pra um jogador, tem assistências por exemplo. Se for assim, vai ser necessário criar uma entidade para cada ação do jogador na partida. Minha ideia seria poder extrair as informações da entidade partida, e os gols serem dependentes de existe a um 1 player e ser armazenado e herdado de partida na entidade player.

**Comment by nicolas-limadev** [comment]
Acredito que a gente não precise utilizar todas as ações do jogador para registro. Existe as seguintes:

- Gol, assistências, cartão amarelo e vermelho, faltas, passes, chutes pra fora, chutes ao gol, desarmes, passes certos, defesas.

Acredito que fica inviável utilizar todos os dados. Mas podemos futuramente inserir em ligas oficiais.


O essencial existir para um baba acontecer entre amigos é gols, Assistência e faltas.

**Comment by raphael-foliveira** [comment]
Entendi. Realmente faz mais sentido, ainda mais quando se fala em outras ações do jogador dentro do jogo.

**Comment by raphael-foliveira** [comment]
> Minha ideia seria poder extrair as informações da entidade partida, e os gols serem dependentes de existir a partir de 1 player, sendo armazenado e herdado de partida na entidade player.

O gol hoje é uma coluna de inteiro na tabela da partida. Como relacionaríamos um Gol a um Player?
Não tem nada que vincule um Gol a um Player e com um inteiro, não tem como relacionar o gol a um Player.
Como funcionaria essa "Herança" de que você está falando?

**Comment by raphael-foliveira** [comment]
Inicialmente, minha idéia é que criemos uma classe abstrata para que tanto Game quanto Match possam herdar, de acordo com a [documentação do TypeOrm](https://orkhan.gitbook.io/typeorm/docs/entity-inheritance). E criar entidades (tabelas) específicas pra cada uma das ações que você mencionou. Essas entidades estariam descritas na entidade base de Game e Match (vamos chamar de BaseGame, por enquanto).

Dessa forma teríamos uma classe `Goal`, que poderia estar descrita como:
```ts
@Entity()
export class Goal {
    @PrimaryGeneratedColumn()
    id;
    
    @ManyToOne(() => Player, (player) => player.goals)
    player;
    
    @ManyToOne(() => BaseGame, (baseGame) => baseGame.goals)
    game;
    
    // ...
}
```

**Comment by nicolas-limadev** [comment]
Você não acha que irá gerar uma quantidade gigantesca de tabelas? Não teria como atribuir a quantidade de ações diretamente ao player como atributo?

**Comment by raphael-foliveira** [comment]
> Não teria como atribuir a quantidade de ações diretamente ao player como atributo?

Isso é impossível. Só podemos adicionar colunas com valores primitivos nas tabelas. Não existe nenhuma maneira de especificar cada ação na mesma tabela que o player.

> Você não acha que irá gerar uma quantidade gigantesca de tabelas?

A solução seria utilizar uma tabela pra cada ação mesmo, por ser um tipo de dado complexo. Isso permite que a gente adicione outras propriedades pra a tabela ação, como por exemplo o momento do jogo que ela aconteceu.
Acho que vale a pena ter uma ação base `BaseAction`, assim como faremos como o `BaseGame`, assim podemos minimizar o número de colunas repetidas.
Ter muitas tabelas em si não é um problema.
