### ISSUE TITLE
Uso dos repositories

### ISSUE THREAD

**Issue by raphael-foliveira** [nicklima-amigos/football-mm#67]
Mexendo no código ao longo desse final de semana, percebi que estou repetindo alguns erros que já estão sendo tratados dentro dos services.

Por exemplo:
Ao criar um `Goal`, preciso encontrar o `Game` especificado pelo campo `gameId` do DTO, e também preciso encontrar um ou dois players, também específicados no DTO nos campos `authorPlayerId` e `assistPlayerId`, sendo o `assistPlayerId` opcional.
Atualmente estamos injetando os repositórios diretamente em `GoalService`, o que faz com que tenhamos que jogar um erro dentro do método `create`, caso alguma das entidades necessárias para criar o `Goal` não seja encontrada:

```ts

@Injectable()
export class GoalService {
  constructor(
    @InjectRepository(Goal) private repository: Repository<Goal>,
    @InjectRepository(Player) private playerRepository: Repository<Player>,
    @InjectRepository(BaseGame) private gameRepository: Repository<BaseGame>,
  ) {}

  async create(createGoalDto: CreateGoalDto) {
    const game = await this.gameRepository.findOne({
      where: { id: createGoalDto.gameId },
    });
    if (!game) {
      throw new NotFoundException('Game not found');
    }
    const player = await this.playerRepository.findOne({
      where: { id: createGoalDto.authorPlayerId },
    });
    if (!player) {
      throw new NotFoundException('Player not found');
    }
    if (createGoalDto.assistPlayerId) {
      const assist = await this.playerRepository.findOne({
        where: { id: createGoalDto.assistPlayerId },
      });
      if (!assist) {
        throw new NotFoundException('Assist player not found');
      }
      return this.repository.save({ ...createGoalDto, game, player, assist });
    }
    return this.repository.save({ ...createGoalDto, game, player });
  }

  // ...
}

```

 Caso a gente permita o uso de `PlayerService` e `GameService`, poderíamos buscar as entidades necessárias utilizando o método `findOne` de cada um desses services, permitindo que a gente reaproveite o erro que já é jogado dentro de todos os services quando uma entidade não é encontrada, como no exemplo do PlayerService:
 
 ```ts
 @Injectable()
export class PlayerService {
  constructor(
    @InjectRepository(Player) private repository: Repository<Player>,
  ) {}

  // ...

  async findOne(id: number) {
    const player = await this.repository.findOne({ where: { id } });
    if (!player) {
      throw new NotFoundException('Player not found');
    }
    return player;
  }

  // ...
  
}
```

Minha sugestão é que utilizemos o sistema de injeção do dependência do nest pra exportar esses services e utilizarmos eles ao invés de utilizar os repositórios de cada entidade diretamente fora de seus próprios módulos. Assim conseguimos encapsular melhor o uso dos repositórios, garantindo que a responsabilidade de acessar o banco para fazer qualquer tipo de ação com a tabela seja responsabilidade do Service que está dentro do módulo que representa a entidade.

**Comment by manoelduran** [comment]
Eu achei uma ótima ideia, isso evitaria re-trabalho e deixaria o codigo mais limpo e seguro

**Comment by raphael-foliveira** [comment]
Li mais sobre o assunto, e o uso dos services dessa maneira poderia levar a outro problema, que seria a criação de dependências circulares.
No caso, teríamos dependência de um service pro outro, sendo que os services estão na mesma camada de implementação. Acaba sendo mais indicado que a camada de service faça uso de dependências que estão abaixo dela, que no nosso caso seria os repositories. 
Por enquanto me parece razoável que a gente continue usando os repositórios necessários dentro de cada service, já que apesar da repetição de código, teremos uma implementação mais sólida, e por conta disso, estou fechando essa issue por enquanto.

Caso alguém discorde e tenha algum ponto legal pra trazer para a discussão, basta reabrir essa issue para retomar a discussão.
